---
- name: klonowanie roli
  hosts: "{{ target | default('all')}}"
  become: yes
  vars:
    - git_repository: "https://github.com/michalrasinskigithub/Ansible_roles.git"
    - git_branch: "main"
    - katalog_roli_ansible: "/etc/ansible/roles"
  tasks:
    - name: utworz katalog o ile nie istnieje
      file:
        path: "{{ katalog_roli_ansible }}""
        state: directory
        mode: '0755'
    - name: wykonaj git checkout na repo
      git:
        repo: "{{ git_repository }}"
        dest: "{{ katalog_roli_ansible }}"
        version: "{{ git_branch }}"

